import Head from 'next/head';
import ArticleList from '../components/ArticleList';

export default function Home({ articles }: any) {
  return (
    <div className='container'>
      <Head>
        <title>Next.js Test</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <h1 className='title'>Next.js Test</h1>
        <ArticleList articles={articles} />
        {/* {articles.map((e) => (
          <h3>{e.title}</h3>
        ))} */}
      </main>

      <footer className='footer'>Testerino</footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=6`
  );
  const articles = await res.json();

  return {
    props: {
      articles,
    },
  };
};
